baseURL = "/"
languageCode = "en-us"
paginate = "20"
summaryLength = "10"
theme = "parsa"
title = "RunHikeRepeat"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Hikiing"
parent = "SHR"
url = "categories/sierrahighroute"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "Ann-Lauriene"
author_image = "images/banner-img.png"
bio = ""
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "This is meta description"
email = ""
google_analitycs_id = "Your ID"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = "*41"
preloader = true
search = true
[params.instafeed]
access_token = ""
enable = true
user_id = "37632450"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
URL = "https://www.instagram.com/ann_lauriene/?hl=en"
icon = "ti-instagram"
